version: '3'

services:
  database:
    build: ./.docker/postgres
    hostname: database
    ports:
      - "5432:5432"
    networks:
      - backend
  pladados:
    build: .
    links:
      - database
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
